<a href="https://colab.research.google.com/github/asghargit/Machinevisionlab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab 1: Introduction to NumPy

Task:
* Your task is to create a Python Class (`ArrayFuncs`) that contains methods to perform the following operations:
 * Elementwise Multiplication (`ele_mult(a,b)`) of N x 1 arrays
 * Inner Product of  N x 1 arrays (`inner_prod(a,b)`)  
 * Outer Product of N x 1 arrays (`outer_prod(a,b)`)
 * Matrix multiplucation of N x M matrices (`mat_mult(a,b)`)

 Note: Don't use the numpy inbuilt inner/outer functions, you must use matrix mutliplication to perform these operations

 Note 2: You do not need to include exception handling (this functionality will not be tested on submission).       

 Note 3: In this notebook we import Numpy as np, this means all the NumPy methods will be implemented as `np.method`.

Learning Outcomes:
* In this lab you will gain experience of constructing a python class with several methods, instantiating the class and testing your methods.
* You will learn basic numpy operations including creating arrays/matrices and the difference between elementwise and matrix multiplication.



# Useful Information

## Numpy Arrays (Matrices):

> As we can see in the image below, we can create arrays in numpy of 1,2,3 (or even greater) dimensions. It is important to note that the 1D array is more properly called a vector, it is not explicit that it represents a row or column. In practice instead of vectors we use arrays of size N x 1 (N can be 2,3,4..), so these arrays can use use numpy functions such as matrix multiplication (and follow the rules of matrix multiplication). For example we can create a 3 x 1 array using np.array([[1],[2],[3]])

![](https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png)


## Matrix Multiplication & Elementwise Multiplication

> In matrix multiplication we require the inner dimension of the two matrices to be the same. The order of the matrices (or 2D arrays is important).

>  In elementwise multiplication if the two arrays are the same size, then each element of the arrays multiplies the corresponding element of the 2nd arrays. If the arrays have at least one equal dimension and the other dimensions are 1 then the NumPy broadcasting rule applies. You can read more about [broadcasting in NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html) here. In this case here where we multiply the 1 x 3 array by the 3 x 3 array, the elements of the 1 x 3 array can be broadcast along the rows of the 3 x 3 array. It is important to note the differnce between elementwise multiplication and traditional matrix multiplication.

![](https://github.com/tonyscan6003/etivities/blob/main/matrx_elem_Mult.jpg?raw=true)

 ## Inner and Outer Product

> We can also complete these inner and outer product computations using matrix multiplication.

 > As we can see in the image below, when we get the outer product of two 1D vectors $u$ & $v$ of size N x 1 we must get the transpose of one of the vectors and perform the computation $uv^T$ . (In linear (matrix) algebra the typical convention is that vectors represent n-rows and 1 column, so the transpose will be 1 row and n-columns). The outer product of two 1D vectors (or numpy arrays) will give an (n x n) 2D array.  

![](https://media.cheggcdn.com/study/8a3/8a3993b3-d3e3-4885-a922-78c73a0f1d76/DC-1776V3.png)

 > In the inner product case we perform matrix multiplication $u^Tv$ such that the result is a scalar value.  





# Create Class
In the code cell below you can create the python class ArrayFuncs

In [ ]:
import numpy as np

class ArrayFuncs:

    # Init Statement
    def __init__(self):
        pass

    def ele_mult(self,a,b):
      return a * b

    def inner_prod(self,a,b):
      return a.T@b
    def outer_prod(self,a,b):
      return a@b.T

    def mat_mult(self,a,b):
      return a@b

# Test Your Class Methods

In the code cell below you can instantiate an instance of your class and create your own tests to determine if your code is working. It is recommended that you check you are correctly creating arrays, use `np.shape` on any array to verify it's size. Check that you get element wise multiplication of two N x 1 arrays, the inner and outer produc are calculated correctly (inner product is scalar, outer product is matrix) and finnally check you correctly can multiply to arrays (ensure inner dimensions match)  We include the `if __name__ == "__main__":` statement so that this code is not executed when uploaded to code grade.

In [ ]:

if __name__ == "__main__":
    # a = np.array([[1],[2],[3]])
    # b = np.array([[23],[24],[25]])
  a = np.array([int(x) for x in input("Enter vector a: ").split(",")]).reshape(-1,1)
  b = np.array([int(x) for x in input("Enter vector b: ").split(",")]).reshape(-1,1)
  af = ArrayFuncs()

  print("elementwise multiplication:\n", af.ele_mult(a,b))

  print("Inner Product:\n ", af.inner_prod(a,b))

  print("Outer Product:\n", af.outer_prod(a,b))


  A = np.array([[1,2,3],[4,5,6],[7,8,9]])
  B = np.array([[23,24,25],[26,27,28],[29,30,31]])

  print("Matrix Multiplication:\n", af.mat_mult(A,B))




Enter vector a: 23,21,10
Enter vector b: 32,5,2
elementwise multiplication:
 [[736]
 [105]
 [ 20]]
Inner Product:
  [[861]]
Outer Product:
 [[736 115  46]
 [672 105  42]
 [320  50  20]]
Matrix Multiplication:
 [[162 168 174]
 [396 411 426]
 [630 654 678]]
